name: Haskell CI

on:
  push:
    branches: 
    - "*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    # Install Nix
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    # # Setup Cachix
    - uses: cachix/cachix-action@v10
      with:
        name: digitallyinduced

    # # Build project
    - working-directory: ./
      run: |
        nix-build
      
    # # Run tests
    - working-directory: ./
      run: |
        nix-shell --run "runghc Test/TestCalculation.hs"
        nix-shell --run "runghc Test/TestController.hs"

    # Echo OK
    - working-directory: ./
      run: nix-shell --run "echo OK"